#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $(basename "$0") [-h]

This script will run a minimum set of checks to an OpenShift cluster

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
--no-info       Disable cluster info commands (default: enabled)
--no-checks     Disable cluster check commands (default: enabled)
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  msg "Something went wrong"
  # shellcheck disable=SC2154
  if [ "${errors}" -gt 0 ]; then
    msg "${RED}Total issues found: ${errors}${NOCOLOR}"
  fi
  die "Exiting" 9
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOCOLOR='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    # shellcheck disable=2034
    NOCOLOR='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

parse_params() {

  while :; do
    case "${1-}" in
    -h | --help)
      usage
      ;;
    -v | --verbose)
      set -x
      ;;
    --no-color)
      NO_COLOR=1
      ;;
    --no-info)
      # shellcheck disable=2034
      INFO=0
      ;;
    --no-checks)
      # shellcheck disable=2034
      CHECKS=0
      ;;
    -?*)
      die "Unknown option: $1"
      ;;
    *)
      break
      ;;
    esac
    shift
  done

  #args=("$@")

  return 0
}

check_command() {
  command -v "${1}" &> /dev/null || die "${RED}${1}${NOCOLOR} command not found"
}

kubeconfig() {
  CONTEXT=$(oc config current-context 2> /dev/null)
  if [ -z "${CONTEXT}" ]; then
    die "${RED}KUBECONFIG not set${NOCOLOR}" 1
  else
    msg "Using ${GREEN}${CONTEXT}${NOCOLOR} context"
  fi
}

oc_whoami() {
  WHOAMI=$(oc whoami 2> /dev/null)
  if [ -z "${WHOAMI}" ]; then
    die "${RED}OpenShift user not found${NOCOLOR}" 1
  else
    echo "${WHOAMI}"
  fi
}