#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if oc auth can-i get clusterversion >/dev/null 2>&1; then
  msg "Cluster version:\n$(oc get clusterversion/version)"
  exit ${OCINFO}
else
  msg "Couldn't get clusterversion, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKNOWN}
