#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if oc auth can-i get pods -A >/dev/null 2>&1; then
  msg "Total pods: $(oc get pods -A --no-headers | wc -l)"
  exit ${OCINFO}
else
  msg "Couldn't get pods, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKNOWN}
