#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

# Check BIOS version to begin with
if oc auth can-i debug node >/dev/null 2>&1; then
  msg "Checking bios versions (${BLUE}using oc debug, it can take a while${NOCOLOR})"
  # shellcheck disable=SC2016
  for node in $(oc get nodes -o go-template='{{range .items}}{{$node := .}}{{range .status.conditions}}{{if eq .type "Ready"}}{{if eq .status "True"}}node/{{$node.metadata.name}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}'); do
    # See https://medium.com/@robert.i.sandor/getting-started-with-parallelization-in-bash-e114f4353691
    ((i=i%PARALLELJOBS)); ((i++==0)) && wait
    (
      if ! BIOSVER=$(oc debug --image="${OCDEBUGIMAGE}" "${node}" -- chroot /host sh -c "cat /sys/class/dmi/id/bios_version" 2>/dev/null); then
        msg "${ORANGE}Error running oc debug in ${node}${NOCOLOR}"
      else
        if [ -n "${BIOSVER}" ]; then
          msg "${node}: ${BIOSVER}"
        else
          msg "Couldn't found /sys/class/dmi/id/bios_version in ${node}"
        fi
      fi
    ) &
  done
  wait
  exit ${OCINFO}
else
  msg "Couldn't debug nodes, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKOWN}
