#!/usr/bin/env bash
# description: Show the images of the containers running in the cluster

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if oc auth can-i get pods -A >/dev/null 2>&1; then
  IMAGES=$(oc get pods -A -o go-template --template='{{range .items}}{{range .spec.containers}}{{printf "%s\n" .image -}} {{end}}{{end}}' | sort -u)
  msg "Images:\n${IMAGES}"
  exit ${OCINFO}
else
  msg "Couldn't get pods, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKNOWN}
