#!/usr/bin/env bash

# lspci -nn shows PCI vendor and device codes (and names)
# Intel XXV710 25GbE SFP28 = 8086:158a
IDS="8086:158a"

if oc auth can-i debug node > /dev/null 2>&1; then
  msg "Checking Intel firmware version (${BLUE}using oc debug, it can take a while${NOCOLOR})"
  for node in $(oc get nodes -o name); do
    if ! FIRMWAREVERS=$(oc debug --image="${OCDEBUGIMAGE}" "${node}" -- chroot /host sh -c "for id in ${IDS}; do for device in \$(lspci -D -d "\${id}" | awk '{ print \$1 }'); do echo -n \"\${device} => \"; lspci -vv -D -s "\${device}" | egrep \"\[V0\]\" | awk '{print \$NF}' ;done;done" 2> /dev/null); then
      msg "${ORANGE}Error running oc debug in ${node}${NOCOLOR}"
    else
      if [ -n "${FIRMWAREVERS}" ]; then
        msg "${node}:\n${FIRMWAREVERS}"
      else
        msg "Couldn't find Intel firmware version in ${node}"
      fi
    fi
  done
else
  msg "Couldn't debug nodes, check permissions"
fi
