#!/usr/bin/env bash
# Updates the checks.md out of scripts in the folders 'headers'

for kind in info pre ssh checks; do
  echo """
# ${kind}
| Script | Description |
| - | - |"""

  for file in $(find ${kind} -type f -executable|sort -V); do
    echo "| [${file}](${file}) | $(grep '^# description:' ${file} | cut -d ":" -f 2-) |"
  done
done
