#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if yq eval ${INSTALL_CONFIG_PATH} >/dev/null; then
  msg "${INSTALL_CONFIG_PATH} seems valid"
else
  errors=$(("${errors}" + 1))
  msg "${INSTALL_CONFIG_PATH} doesn't seem valid"
fi
