#!/usr/bin/env bash

# https://access.redhat.com/solutions/4250221

if oc auth can-i get routes -n openshift-monitoring > /dev/null 2>&1; then
  alert_url=$(oc -n openshift-monitoring get routes/alertmanager-main -o json | jq -r .spec.host)
  alerts=$(curl -s -k -H "Authorization: Bearer $(oc -n openshift-monitoring sa get-token prometheus-k8s)" https://$alert_url/api/v1/alerts | jq '.data[].labels |  {alert: .alertname, severity: .severity} | select(.severity == "warning")')

  if [[ -n ${alerts} ]]; then
    ALERTS=$(echo "${alerts}" | jq .)
    msg "Alerts currently firing: ${RED}${ALERTS}${NOCOLOR}"
    errors=$(("${errors}"+1))
  fi
else
  msg "Couldn't get routes, check permissions"  
fi