#!/usr/bin/env bash

if oc auth can-i get pods -n openshift-authentication-operator >/dev/null 2>&1; then
  msg "Checking for a hung kubelet..."
  # shellcheck disable=SC2016
  node=$(oc get pods -n openshift-authentication-operator -o json | jq -r .items[0].spec.nodeName)
  pod=$(oc get pods -l app=authentication-operator -n openshift-authentication-operator -o json  | jq -r .items[0].metadata.name)
  if ! AUTH_OPERATOR_MEMORY=$(oc exec -n openshift-authentication-operator $pod --  ps -o rss -p 1 --no-headers); then
      msg "${ORANGE}Error running oc exec on pod openshift-authentication-operator/${pod}${NOCOLOR}"
    else
      if [ -n "${AUTH_OPERATOR_MEMORY}" ] && [ "${AUTH_OPERATOR_MEMORY}" -gt 2097152 ]; then # more than 2GB is a bad sign
        msg "${RED}High memory usage detected for openshift-authentication-operator, which likely means that kubelet on ${node} is hung. Terminate the pod to remediate${NOCOLOR}"
        errors=$(("${errors}" + 1))
      fi
    fi
else
  msg "Couldn't get pods, check permissions"
fi
