#!/usr/bin/env bash

if oc auth can-i get clusterversion > /dev/null 2>&1; then
  clusterversion_msgs=$(oc get clusterversion -o json | jq '.items[].status.conditions[] | select ((.status == "True") and (.type == "Failing") and (.message != null)) | { message: .message }' )                                                                    
  count_errors=$(echo ${clusterversion_msgs} | jq .message |wc -l)
  if [[ ${count_errors} -ge 1 ]]; then
    final=""
    OLDIFS=$IFS
    IFS=$'\n'

    for message in $(echo ${clusterversion_msgs} | jq .message); do
        final="${final} ${message}"
    done
    IFS=${OLDIFS}
    msg "Clusterversion error status message: ${final}"
    errors=$(("${errors}"+1))
  fi
else
  msg "Couldn't get clusterversion, check permissions"
fi

