#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if oc auth can-i get nodes >/dev/null 2>&1; then
  scheduable_controllers=$(oc get nodes -o json | jq '.items[] | { name: .metadata.name, scheduable: .spec.taints, control: .metadata.labels."node-role.kubernetes.io/master" } | select((.control == "") and (.scheduable == null))')
  if [[ -n ${scheduable_controllers} ]]; then
    SCHEDCTRL=$(echo "${scheduable_controllers}" | jq '. | { name: .name }')
    msg "Controllers ${RED}Scheduable${NOCOLOR}: ${SCHEDCTRL}"
    errors=$(("${errors}" + 1))
  fi
else
  msg "Couldn't get nodes, check permissions"
fi
