#!/usr/bin/env bash
# https://access.redhat.com/solutions/5709711

if oc auth can-i debug node > /dev/null 2>&1; then
  msg "Checking if ports 22623/tcp and 22624/tcp are blocked (${BLUE}using oc debug, it can take a while${NOCOLOR})"
  for node in $(oc get nodes -o name); do
    # shellcheck disable=2016
    if oc debug "${node}" -- chroot /host sh -c \
        "iptables -C FORWARD -p tcp --dport 22623 -j REJECT --reject-with icmp-port-unreachable &>/dev/null && \
         iptables -C FORWARD -p tcp --dport 22624 -j REJECT --reject-with icmp-port-unreachable &>/dev/null && \
         iptables -C OUTPUT -p tcp --dport 22623 -j REJECT --reject-with icmp-port-unreachable &>/dev/null && \
         iptables -C OUTPUT -p tcp --dport 22624 -j REJECT --reject-with icmp-port-unreachable &>/dev/null" 2> /dev/null; then
      msg "${RED}iptables rules for 22623/tcp or 22624/tcp found in ${node}${NOCOLOR}"
      errors=$(("${errors}"+1))
    fi
  done
else
  msg "Couldn't debug nodes, check permissions" 
fi