#!/usr/bin/env bash

if oc auth can-i get network/cluster > /dev/null 2>&1 &&  oc auth can-i debug node > /dev/null 2>&1; then
  msg "Checking Network Type"
  network_type=$(oc get network/cluster -ojson | jq -r .status.networkType)
  if [[ $network_type != "OVNKubernetes" ]]; then
    msg "MTU not supported for clusters using $network_type"
  else
    msg "Collecting MTUs... (${BLUE}it can take a while${NOCOLOR})"
    for node in $(oc get nodes -o name); do
      # Get all the information in a single debug to avoid rescheduling unneeded pods
      # then convert the output into an array for easily consumption
      # shellcheck disable=2016
      mapfile -t MTUS < <( oc debug "${node}" -- chroot /host sh -c 'export EXTBR="br-ex"; export OVNBR="ovn-k8s-mp0"; export BMINTERFACE=$(ovs-vsctl list-ports "${EXTBR}" | grep -v patch) ; nmcli -g GENERAL.MTU dev show "${BMINTERFACE}"; nmcli -g GENERAL.MTU dev show "${EXTBR}"; nmcli -g GENERAL.MTU dev show "${OVNBR}"' 2> /dev/null )
      # br-ex mtu should match baremetal interface
      if [ "${MTUS[0]}" -ne "${MTUS[1]}" ];then
        msg "Wrong MTU in ${node}: baremetal-interface MTU != br-ex MTU"
        errors=$(("${errors}"+1))
      fi
      # ovn-k8s-mp0 mtu should be 100 uds less than br-ex
      if [ $(("${MTUS[1]}"-100)) -ne "${MTUS[2]}" ];then
        msg "Wrong MTU in ${node}: ovn-k8s-mp0 MTU != br-ex - 100"
        errors=$(("${errors}"+1))
      fi
    done
  fi
else
      msg "Couldn't debug nodes, check permissions" 
fi