#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

error=false

if oc auth can-i get co >/dev/null 2>&1; then
  bad_operators=$(oc get co --no-headers | grep -E -civ 'True.*False.*False')
  if [[ ${bad_operators} -ge 1 ]]; then
    BADOPS=$(oc get co --no-headers | grep -E -iv 'True.*False.*False')
    msg "Operators in Bad State (${bad_operators}):\n${RED}${BADOPS}${NOCOLOR}"
    errors=$(("${errors}" + 1))
    error=true
  fi
  if [ ! -z "${ERRORFILE}" ]; then
    echo $errors >${ERRORFILE}
  fi
  if [[ "$error" == true ]]; then
    exit ${OCERROR}
  else
    exit ${OCOK}
  fi

else
  msg "Couldn't get co, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKOWN}
