#!/usr/bin/env bash
# description: Checks if there are OVN pods thrashing

THRASHINGMSG="Changing chassis for lport"
NAMESPACE="openshift-ovn-kubernetes"

error=false

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if [[ $(oc get network/cluster -o jsonpath={.spec.networkType}) != "OVNKubernetes" ]]; then
  msg "This check only works for OVNKubernetes SDN"
  exit ${OCSKIP}
else
  if oc auth can-i get pods -n ${NAMESPACE} >/dev/null 2>&1; then
    if oc auth can-i get pods --subresource=log -n ${NAMESPACE} >/dev/null 2>&1; then
      for pod in $(oc get pods -o name -n ${NAMESPACE} -l app=ovnkube-node); do
        numerrors=$(oc logs -n ${NAMESPACE} ${pod} -c ovn-controller | grep "${THRASHINGMSG}" -c)
        if [[ ${numerrors} -gt ${THRASHING_THRESHOLD} ]]; then
          msg "${RED}${pod} port thrashing errors detected${NOCOLOR}"
          errors=$(("${errors}" + 1))
          error=true
        fi

      done
      if [ ! -z "${ERRORFILE}" ]; then
        echo $errors >${ERRORFILE}
      fi
      if [[ $error == true ]]; then
        exit ${OCERROR}
      else
        exit ${OCOK}
      fi
    else
      msg "Couldn't get pods logs, check permissions"
      exit ${OCSKIP}
    fi
  else
    msg "Couldn't get pods, check permissions"
    exit ${OCSKIP}
  fi
fi
exit ${OCUNKNOWNN}
