#!/usr/bin/env bash

if oc auth can-i get pods -A > /dev/null 2>&1; then
  restarts=$(oc get pods -o json -A| jq -r ".items[] | { name: .metadata.name, project: .metadata.namespace, restarts: .status.containerStatuses[].restartCount } | select(.restarts > $RESTART_THRESHOLD)")
  if [[ -n $restarts ]]; then
    RESTARTS=$(echo "${restarts}" | jq .)
    msg "Pods that have a high restart count (> $RESTART_THRESHOLD):\n${RED}${RESTARTS}${NOCOLOR}"
    errors=$(("${errors}"+1))
  fi
else
  msg "Couldn't get all pods, check permissions" 
fi