#!/usr/bin/env bash

[ -z ${UTILSFILE} ] && source $(echo "$(dirname ${0})/../utils")

if oc auth can-i get pods -A >/dev/null 2>&1; then
  terminating_pods=$(oc get pods -A | grep -c 'Terminating')
  if [[ $terminating_pods -ge 1 ]]; then
    TERMPODS=$(oc get pods -A | grep 'Terminating')
    msg "Pods in Terminating state ($terminating_pods):\n${RED}${TERMPODS}${NOCOLOR}"
    errors=$(("${errors}" + 1))
  fi
  if [ ! -z "${ERRORFILE}" ]; then
    echo $errors >${ERRORFILE}
  fi
  if [ "errors" != "0" ]; then
    exit ${OCERROR}
  else
    exit ${OCOK}
  fi
else
  msg "Couldn't get all pods, check permissions"
  exit ${OCSKIP}
fi
exit ${OCUNKOWN}
